apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabels:
      app-node: node-js-app
  template:
    metadata:
      name: nodejs-pod
      labels:
        app-node: node-js-app
    spec:
      containers:
        - name: nodejs-app
          image: khannedy/nodejs-web:1
          ports:
            - containerPort: 3000
          resources:
            requests:
              # milli core
              cpu: 1000m
              # mebibyte
              memory: 250Mi
            limits:
              # milli core
              cpu: 2000m
              # mebibyte
              memory: 500Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nodejs-new
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: v1
kind: Service
metadata:
  name: lb-hpa
spec:
  type: LoadBalancer
  selector:
    app-node: node-js-app
  ports:
    - port: 80
      targetPort: 3000
