apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-1
  labels:
    app_deploy: app_nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app_type: nodejs
  template:
    metadata:
      name: nodejs-app
      labels:
        app_type: nodejs
    spec:
      containers:
      - name: nodejs-app-container
        image: khannedy/nodejs-web:3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-lb-gty
spec:
  type: LoadBalancer
  selector:
    app_type: nodejs
  ports:
    - port: 80
      targetPort: 3000