apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapapp
data:
  APPLICATION: My cool APP
  VERSION: 1.0.0
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: replic-set
spec:
    replicas: 3
    selector:
        matchLabels:
            name: nodejs-env
    template:
          metadata:
              name: nodejs-env
              labels:
                  name: nodejs-env
          spec:
              containers:
                  - name: nodejs-env
                    image: khannedy/nodejs-env
                    ports:
                    -  containerPort: 3000
                    volumeMounts:
                      - mountPath: /app/html
                        name: html
                    envFrom:
                      - configMapRef:
                          name: configmapapp

              volumes:
                - name: html
                  emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lbgateway
spec:
  type: LoadBalancer
  selector:
    name: nodejs-env
  ports:
    - port: 8080
      targetPort: 3000
    
                
        