apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-label
  labels:
    Team: sysadmin
    Version: "1.1"
    environment: Development
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80

