apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-node-selector
spec:
  replicas: 3
  selector:
      matchLabels:
          app: node-selector
  template:
        metadata:
            name: nginx-pod
            labels:
                app: node-selector
        spec:
            nodeSelector:
                hardisk: "ssd"
            containers:
                - name: nginx-container-node-selector
                  image: nginx:latest
                  ports:
                  -  containerPort: 80