apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: replic-set-multi-pod
    labels:
        name: replic-set-multi-pod
spec:
    replicas: 3
    selector:
        matchLabels:
            name: multi-pod-app
    template:
        metadata:
            name: multi-pod
            labels:
                name: multi-pod-app
        spec:
            containers:
                - name: nginx-container
                  image: nginx:latest
                  ports:
                  -  containerPort: 80
                
                - name: app-nodejs-container
                  image: khannedy/nodejs-web
                  ports:
                  -  containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-gateway-app
spec:
  selector:
    name: multi-pod-app
  ports:
  - port: 8080
    targetPort: 80
    name: nginx
  - port: 8081
    targetPort: 3000
    name: nodejs-app
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-container
      image: nginx

    
                
        