apiVersion: v1
kind: Secret
metadata:
  name: secret-version
stringData:
  VERSION: 1.0.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-app
data:
  APPLICATION: Cool_APP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: replic-set-nodejs-app
spec:
    replicas: 3
    selector:
        matchLabels:
            name: nginx-pod-rc
    template:
        metadata:
            name: nginx-pod
            labels:
               name: nginx-pod-rc
        spec:
            containers:
                - name: nodejs-app-env
                  image: khannedy/nodejs-env
                  ports:
                  -  containerPort: 3000
                  envFrom:
                    - configMapRef:
                        name: configmap-app
                    - secretRef:
                        name: secret-version
---
apiVersion: v1
kind: Service
metadata:
  name: lbgateway
spec:
  type: LoadBalancer
  selector:
    name: nginx-pod-rc
  ports:
    - port: 80
      targetPort: 3000
    
                
        