apiVersion: v1
kind: Pod
metadata:
  name: nodejs-volume-app
spec:
  volumes:
    - name: html 
      hostPath:
        path: /home/zack/Documents/kube_learn/dockerfile
        type: DirectoryOrCreate
  containers:
    - name: nginx-volume
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /app/html
          name: html