apiVersion: v1
kind: Service
metadata:
  name: external-service
  labels:
    sipd: test
spec:
  ports:
    - port: 80

---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: endpoint-external
  labels:
    sipd: test
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - 103.245.225.173

---
apiVersion: v1
kind: Pod
metadata: 
  name: curl-test-endpoint
spec:
  containers:
    - name: curl-nginx
      image: nginx:latest