apiVersion: v1
kind: Pod
metadata:
  name: node-selecttor-pod
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: nginx-node-selector
      image: nginx:latest
      ports:
        - containerPort: 80