apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
spec:
    replicas: 3
    selector:
        app: lalungguh
    template:
        metadata:
            name: nginx-template-container
            labels:
                app: lalungguh
        spec:
            containers:
                - name: nginx-container
                  image: nginx:latest
                  ports:
                   - containerPort: 80
                