apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx-replic
    labels:
        app: nginx-replic
spec:
    replicas: 3
    selector:
        matchExpressions:
            - key: Type
              operator: In
              values: 
                - nginx
    template:
        metadata:
            name: nginx-pod
            labels:
                Type: nginx
        spec:
            containers:
                - name: nginx-container
                  image: nginx:latest
                  ports:
                  -  containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    Type: nginx
  ports:
  - port: 8080
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  labels:
    name: myapp-curl-test
spec:
  containers:
  - name: curl-test-container
    image: nginx:latest