apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: web-server-replica-1
    labels:
        app: replica-web-server 
spec:
    replicas: 3
    selector:
        matchLabels:
            content: nginx-pod-rc
    template:
        metadata:
            name: nginx-pod
            labels:
                content: nginx-pod-rc
        spec:
            containers:
                - name: nginx-container
                  image: nginx:latest
                  ports:
                  -  containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-namespace-default
  labels:
    service: nodeport
spec:
  type: NodePort
  selector:
    content: nginx-pod-rc
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30200