apiVersion: v1
kind: CronJob
metadata:
  name: pod-name
spec:
  schedule: "* * * *"
  jobTemplate:
    spec:
        selector:
            matchExpressions:
                - key: test
                operator: In
                values:
                    - CronJob
        template:
            metadata:
                name: template-daemosets-node-selector
            spec:
                nodeSelector:
                    gpu: "true"
                containers:
                    - name: container-name
                    image: image-name
                    ports:
                        - containerPort: 80