apiVersion: v1
kind: DaemonSet
metadata:
  name: pod-name
spec:
  selector:
    matchExpressions:
        - key: test
          operator: In
          values:
            - daemonset
  template:
    metadata:
        name: template-daemosets-node-selector
    spec:
        nodeSelector:
            gpu: "true"
        containers:
            - name: container-name
              image: image-name
              ports:
                - containerPort: 80