apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
    labels:
        label-key: label-value
    annotations:
        anno-key: anno-value
spec:
    replica: 3
    selector:
        labels-key: value-labels #selector dan labels yang berada di metadata template harus sama karena akan menjadi parameter apakah replicanya udah bener apa belom
    template:
        metadata:
            name: nginx-template
            labels:
                labels-key: value-labels #selector dan labels yang berada di metadata template harus sama
        spec:
            containers:
                - name: nginx-container
                  image: nginx:latest
                  ports:
                  -  containerPorts: 80
            readinessProbe:
                httpGet:
                    path: /
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 1
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 5
                