apiVersion: v1
kind: ReplicaSet
metadata:
  name: pod-name
spec:
  Replica: 3
  selector:
            matchLabels:
                name: nginx-pod-rc
  template:
        metadata:
            name: nginx-pod
            labels:
                Team: Devops
        spec:
            nodeSelector:
                gpu: "true"
            containers:
                - name: nginx-container
                  image: nginx:latest
                  ports:
                  -  containerPorts: 80